/* Optional: PLAYWRIGHT_MODULE=/absolute/path/to/playwright CHROMIUM_PATH=/path/to/chrome node tests/browser-smoke.cjs */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../docs');const output=path.resolve(__dirname,'../../qa');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(file===root+'/')file=path.join(root,'index.html');if(!file.startsWith(root)){res.writeHead(403);res.end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);res.end('Missing');return;}res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.pdf':'application/pdf'})[path.extname(file)]||'application/octet-stream');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:process.env.SPARTICUZ_MODULE?(await import(process.env.SPARTICUZ_MODULE)).default.args:['--no-sandbox','--disable-dev-shm-usage']});try{const page=await browser.newPage({viewport:{width:1440,height:1080},timezoneId:'Europe/London',acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:new Date('2026-09-25T10:00:00+01:00')});await page.goto(base);await page.waitForSelector('.kpis');await page.screenshot({path:output+'/overview.png',fullPage:true});assert.ok((await page.locator('.kpi').first().textContent()).includes('22.0'));
for(const tab of ['plan','activities','volume','fitness','methods']){await page.locator(`.nav [data-tab="${tab}"]`).click();await page.waitForTimeout(50);assert.ok(await page.locator('h1').isVisible());await page.screenshot({path:output+'/'+tab+'.png',fullPage:tab!=='plan'});}
await page.locator('.nav [data-tab="activities"]').click();await page.locator('tr[data-activity]').first().click();await page.waitForSelector('#detail[open]');await page.locator('[data-action="apply-thursday"]').click();await page.waitForTimeout(100);assert.ok((await page.locator('#detail').textContent()).includes('Threshold 1'));await page.locator('#range-start').fill('3');await page.locator('#range-end').fill('6');await page.locator('[data-action="inspect-range"]').click();assert.ok((await page.locator('#range-output').textContent()).includes('4:'));await page.screenshot({path:output+'/activity-detail.png',fullPage:false});for(const tab of ['splits','laps','notes']){await page.locator(`[data-activity-view="${tab}"]`).click();await page.waitForTimeout(30);}await page.locator('#note-rpe').fill('6');await page.locator('#note-text').fill('QA note');await page.locator('[data-action="save-notes"]').click();await page.locator('[data-action="close"]').click();
await page.locator('.nav [data-tab="plan"]').click();await page.locator('.plan-row[data-session="2026-09-29"]').click();await page.locator('[data-edit="2026-09-29"]').click();await page.locator('[data-step-row="0"] [data-field="value"]').fill('6');await page.locator('[data-action="save-editor"]').click();assert.ok((await page.locator('#editor-stats').textContent()).includes('17.00'));
const downloadPromise=page.waitForEvent('download');await page.locator('[data-action="download-fit"]').click();const download=await downloadPromise;await download.saveAs(output+'/edited-workout.fit');assert.ok(fs.statSync(output+'/edited-workout.fit').size>100);await page.screenshot({path:output+'/editor.png',fullPage:false});await page.locator('[data-action="close"]').click();await page.reload();await page.waitForSelector('.plan-row');assert.ok((await page.locator('.plan-row[data-session="2026-09-29"]').textContent()).includes('17'));
await page.locator('.nav [data-tab="fitness"]').click();await page.locator('#race-time').fill('1:25:45');await page.locator('[data-action="calculate"]').click();assert.ok((await page.locator('#race-result').textContent()).includes('2:58'));
const backupPromise=page.waitForEvent('download');await page.locator('[data-action="backup"]').first().click();const backup=await backupPromise;await backup.saveAs(output+'/backup.json');const b=JSON.parse(fs.readFileSync(output+'/backup.json'));assert.equal(b.overrides['2026-09-29'].steps[0].value,6);
await page.setViewportSize({width:390,height:844});await page.locator('.nav [data-tab="overview"]').click();await page.screenshot({path:output+'/mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('.nav [data-tab="plan"]').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('.plan-row[data-session="2026-09-29"]').click();await page.locator('[data-edit="2026-09-29"]').click();await page.screenshot({path:output+'/mobile-editor.png',fullPage:false});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('[data-action="close"]').click();
// Synthetic stream fixture, isolated to this browser. No fixture is published.
await page.setViewportSize({width:1440,height:1080});
const t=[],d=[],hr=[],moving=[];for(let sec=0;sec<=3060;sec+=10){t.push(sec);const moveSec=sec<=1200?sec:sec<=1260?1200:sec-60;d.push(moveSec/3000*10000);hr.push(150);moving.push(!(sec>1200&&sec<=1260));}
const fixture={id:999999999,type:'Run',name:'Synthetic stream check',start_date_local:'2026-09-25T08:00:00',start_date:'2026-09-25T07:00:00Z',distance:10000,moving_time:3000,elapsed_time:3060,average_heartrate:150,total_elevation_gain:10,streams_file:'streams/999999999.json',detail_status:'available'};
await page.route('**/workouts.json',r=>r.fulfill({json:{updated:'2026-09-25T09:00:00Z',activities:[fixture],sync:{pending_details:0,pending_streams:0}}}));
await page.route('**/streams/999999999.json',r=>r.fulfill({json:{streams:{time:{data:t},distance:{data:d},heartrate:{data:hr},moving:{data:moving}}}}));
await page.locator('[data-action="refresh"]').first().click();await page.locator('.nav [data-tab="activities"]').click();await page.locator('tr[data-activity="999999999"]').click();await page.waitForFunction(()=>document.querySelector('#detail')?.textContent.includes('1.333'));assert.ok((await page.locator('#detail').textContent()).includes('1:00'));await page.locator('#range-start').fill('0');await page.locator('#range-end').fill('10');await page.locator('[data-action="inspect-range"]').click();assert.ok((await page.locator('#range-output').textContent()).includes('5:00/km'));await page.locator('[data-action="close"]').click();
// Self-contained preview must run from file:// and export a verified FIT.
await page.unrouteAll();await page.goto('file://'+path.resolve(__dirname,'../PREVIEW.html'));await page.waitForSelector('.kpis');assert.ok((await page.locator('body').textContent()).includes('Offline preview'));await page.locator('.nav [data-tab="plan"]').click();await page.locator('.plan-row[data-session="2026-09-29"]').click();await page.locator('[data-edit="2026-09-29"]').click();const off=page.waitForEvent('download');await page.locator('[data-action="download-fit"]').click();await (await off).saveAs(output+'/offline-preview.fit');
assert.deepEqual(errors,[]);console.log('PASS: detailed feed, mixed stop stream, clean efficiency, block metrics, standalone file preview and offline FIT export.');console.log('PASS: all tabs, workout revision, block inspection, notes, edited FIT download, persistence, race calculator, backup, mobile overflow.');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exit(1);});
